nc: 1
scales:
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 10
  - [[-1, 6], 1, Concat, [1]]  # 11 cat backbone P4
  - [-1, 3, C2f, [512, False]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 13
  - [[-1, 4], 1, Concat, [1]]  # 14 cat backbone P3
  - [-1, 3, C2f, [256, False]]  # 15

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]  # 16
  - [[-1, 2], 1, Concat, [1]]  # 17 cat backbone P2
  - [-1, 1, C2f, [128, False]]  # 18

  - [-1, 1, Conv, [128, 3, 2]]  # 19
  - [[-1, 15], 1, Concat, [1]]  # 20 cat head P3
  - [[-1, 3], 1, Concat, [1]]  # 21 cat head P3 and backbone B3
  - [-1, 3, C2f, [256, False]]  # 22

  - [-1, 1, Conv, [256, 3, 2]]  # 23
  - [[-1, 12], 1, Concat, [1]]  # 24 cat head P4
  - [[-1, 5], 1, Concat, [1]]  # 25 cat head P4 and backbone B4
  - [-1, 3, C2f, [512, False]]  # 26

  - [-1, 1, Conv, [512, 3, 2]]  # 27
  - [[-1, 9], 1, Concat, [1]]  # 28 cat head P5
  - [-1, 3, C2f, [1024, False]]  # 29

  - [[18, 22, 26, 29], 1, Detect, [nc]]  # 30 Detect(P2, P3, P4, P5)
